TodoListRazorPages/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace TodoListRazorPages.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TodoListRazorPages/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TodoListRazorPages.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

TodoListRazorPages/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TodoListRazorPages.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TodoListRazorPages/Pages/Todos/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;
using TodoListRazorPages.Data;

namespace TodoListRazorPages.Pages.Todos
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [TempData]
        public string Message { get; set; }

        [BindProperty]
        public List<TodoItem> TodoItems { get; set; }

        public void OnGet()
        {
            TodoItems = _db.TodoItems.OrderBy(x => x.IsDone).ToList();
        }

        public IActionResult OnPostSave()
        {
            if (ModelState.IsValid)
            {
                _db.UpdateRange(TodoItems);
                _db.SaveChanges();
                Message = "The changes has been saved succesfully.";
                return RedirectToPage();
            }

            return Page();
        }

        public IActionResult OnPostDelete()
        {
            _db.RemoveRange(TodoItems.Where(x => x.IsDone));
            _db.SaveChanges();
            return RedirectToPage();
        }
    }
}

TodoListRazorPages/Pages/Todos/New.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TodoListRazorPages.Data;

namespace TodoListRazorPages.Pages.Todos
{
    public class NewModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public NewModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public TodoItem NewTodo { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                _db.Add(NewTodo);
                _db.SaveChanges();
                return RedirectToPage("/Todos/Index");
            }
            return Page();
        }
    }
}

TodoListRazorPages/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TodoListRazorPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoListRazorPages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">TodoListRazorPages</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Todos/Index">Todos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TodoListRazorPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TodoListRazorPages/Pages/Todos/Index.cshtml
@page
@model TodoListRazorPages.Pages.Todos.IndexModel
@{            
    ViewData["Title"] = "Todos";
}

@if (!string.IsNullOrEmpty(Model.Message))
{
    <div class="alert alert-info">
        @Model.Message
    </div>
}

<div class="my-2">
    <a asp-page="/Todos/New">New Todo</a>
</div>

<form method="post">
    @for (int i = 0; i < Model.TodoItems.Count; i++)
    {
        <div class="d-flex align-items-baseline mb-2">
            <input type="hidden" asp-for="TodoItems[i].Id" />
            <input type="checkbox" asp-for="TodoItems[i].IsDone" class="mr-2" />
            <input type="text" asp-for="TodoItems[i].Title" class="form-control mr-2" />
            <span asp-validation-for="TodoItems[i].Title" class="text-danger"></span>
        </div>
    }

    <button class="btn btn-primary mt-2" asp-page-handler="save">Save All</button>
    <button class="btn btn-danger mt-2" asp-page-handler="delete">Delete Completed Tasks</button>
</form>

TodoListRazorPages/Pages/Todos/New.cshtml
@page
@model TodoListRazorPages.Pages.Todos.NewModel
@{      
    ViewData["Title"] = "New Todo";
}

<h1>New Todo</h1>

<form method="post">
    <div class="form-group">
        <label asp-for="NewTodo.Title"></label>
        <input type="text" asp-for="NewTodo.Title" class="form-control" />
        <span asp-validation-for="NewTodo.Title" class="text-danger"></span>
    </div>

    <button class="btn btn-primary">Save</button>
</form>